# Generated by Django 3.2.13 on 2022-05-02 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20220501_2337'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='food',
            table=None,
        ),
    ]
