# Generated by Django 3.2.13 on 2022-05-02 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_food_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
    ]
