# Generated by Django 3.2.13 on 2022-05-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_food_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='index',
        ),
        migrations.AlterField(
            model_name='food',
            name='countries_en',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredients_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='food',
            name='product_name',
            field=models.CharField(max_length=1000),
        ),
    ]
