# -*- coding: utf-8 -*-
"""standardize.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kalq78aTzJ2V9c4LD1I5mwH9KE0WJdIy
"""

!pip install langdetect
import pandas as pd
from langdetect import detect

#basePath = "/content/drive/My Drive/"
#df = pd.read_csv(basePath + '/filtered_data.csv', on_bad_lines='skip',sep='\t')
df = pd.read_csv('filtered_data.csv', on_bad_lines='skip',sep='\t')

df['detect'] = df['ingredients_text'].str.lower()
df = df[df['detect'].str.islower()]
df['detect'] = df['ingredients_text'].apply(detect)

df = df[df['detect'] == 'en']
df['ingredients_text'] = df['ingredients_text'].str.lower()

df_final = df.loc[:, df.columns!='detect']

df_final.to_csv('Finalfiltered_data.csv')